---
- name: Configuring Example Tenant
  hosts: "{{ lookup('env','ACI_HOST') }}"
  collections:
   - cisco.aci
   - zjpeterson.aci
  connection: local
  gather_facts: yes

  tasks:
  - name: Create a New Tenant
    aci_tenant:
      host: "{{ lookup('env','ACI_HOST') }}"
      username: "{{ lookup('env','ACI_USERNAME') }}"
      password: "{{ lookup('env','ACI_PASSWORD') }}"
      tenant: "{{ tenant }}"
      description: "Tenant configured by Ansible"
      validate_certs: no
      state: present 
      output_path: 'config.json'