---
- name: Configuring Example Tenant
  hosts: apic1
  collections:
   - cisco.aci
  connection: local
  gather_facts: yes

  tasks:
  - name: Create a New Tenant
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: admin
      password: 12345C1scoUC$
      tenant: "Partner-Training12345"
      description: "Tenant configured by Ansible"
      validate_certs: no
      state: present 
      output_path: 'config.json'